better readability and options handing

diff --git a/cider b/cider
--- a/cider
+++ b/cider
@@ -18,6 +18,7 @@ o="\033[0m"  # off
 # die a graceful death!
 die() {
   echo "$PROG: $*" >&2
+  echo "Try \`$PROG -h' for more information" >&2
   exit 1
 }
 
@@ -158,6 +159,7 @@ _awk() {
     function die(err)
     {
       print prog ": " err > "/dev/stderr"
+      print "Try `" prog " -h\47 for more information." > "/dev/stderr"
       next
     }
     function validate_cidr(a)
@@ -209,58 +211,71 @@ _awk() {
 # parse short options
 OPTIND=1
 while getopts ":c:ehv" opt; do
-  shift $((OPTIND-1))
   case $opt in
     c)
-      if [ $# -ge 1 ]; then
-        case $OPTARG in
-          1) ACTION=quad2num;;
-          2) ACTION=num2quad;;
-          3) ACTION=quad2hex;;
-          4) ACTION=hex2quad;;
-          5) ACTION=bit2addr;;
-          6) ACTION=addr2bit;;
-          *) die "invalid option argument: $OPTARG";;
-        esac
-      else
-        short
-        exit 1
+      if [[ "$LASTOPT" == "$opt" ]]; then
+        die "only one \`-$opt' may be specified"
       fi
+
+      case $OPTARG in
+        1) ACTION=quad2num;;
+        2) ACTION=num2quad;;
+        3) ACTION=quad2hex;;
+        4) ACTION=hex2quad;;
+        5) ACTION=bit2addr;;
+        6) ACTION=addr2bit;;
+        *) die "invalid option argument -- '$OPTARG'";;
+      esac
+      LASTOPT=$opt; LASTOPTARG=$OPTARG
       ;;
     e)
-      if [ $# -ge 1 ]; then
-        ACTION=expand_cidr
-      else
-        short
-        exit 1
+      if [[ "$LASTOPT" == "$opt" ]]; then
+        die "only one \`-$opt' may be specified"
       fi
+
+      ACTION=expand_cidr
+      LASTOPT=$opt
       ;;
     h)
-      if [ $# -eq 0 ]; then
-        usage; exit 0
-      else
-        short; exit 1
-      fi
+      if [[ $# -ne 1 || $OPTIND -eq 1 ]]; then short; exit 1; fi
+      usage; exit 0
       ;;
     v)
-      if [ $# -eq 0 ]; then
-        echo "$PROG $VERSION"
-        echo "Written by $AUTHOR"
-        exit 0
-      else
-        short; exit 1
-      fi
+      if [[ $# -ne 1 || $OPTIND -eq 1 ]]; then short; exit 1; fi
+      echo "$PROG $VERSION"
+      echo "Written by $AUTHOR"
+      exit 0
       ;;
-   \?) die "invalid option: -$OPTARG";;
+    :) die "option requires an argument -- '$OPTARG'";;
+   \?) die "invalid option -- '$OPTARG'";;
   esac
 done
+shift $((OPTIND-1))
 
-# main
-if [ $# -eq 0 ]; then
-  # empty arguments
+# check for empty arguments
+if [[ -n "$LASTOPT" && $# -eq 0 ]]; then
+  case $LASTOPT in
+    c)
+       case $LASTOPTARG in
+         1) die "missing argument: [ADDRESS]";;
+         2) die "missing argument: [ADDRESS]";;
+         3) die "missing argument: [ADDRESS]";;
+         4) die "missing argument: [ADDRESS]";;
+         5) die "missing argument: [NETMASK]";;
+         6) die "missing argument: [NETMASK]";;
+         *) short; exit 1;;
+       esac
+       ;;
+    e) die "missing argument: [ADDRESS]";;
+    *) short; exit 1;;
+  esac
+elif [ $# -eq 0 ]; then
   short
   exit 1
-elif [[ "$1" == "-" ]]; then
+fi
+
+# main
+if [[ "$1" == "-" ]]; then
   # read from stdin
   _awk $ACTION -
 else
diff --git a/crib b/crib
--- a/crib
+++ b/crib
@@ -77,7 +77,7 @@ asn2ip() {
   if [[ -z "$asn" || "$asn" == "-" ]]; then
     cat -
   else
-    cat <<<"$asn"
+    cat - <<<"$asn"
   fi | \
   $PARALLEL sh -c 'whois -h whois.radb.net !g{} > /tmp/{}.xargs' 2>/dev/null
 
@@ -102,7 +102,7 @@ cc2asn() {
   if [[ -z "$cc" || "$cc" == "-" ]]; then
     cat -
   else
-    cat <<<"$cc"
+    cat - <<<"$cc"
   fi |
   ($PARALLEL curl -s -A $ua $url/{} | grep -Eo 'AS[0-9]+' &) |
   uniq -c |
@@ -118,9 +118,9 @@ cc2ip() {
   validate_cc $cc
 
   if [[ -z "$cc" || "$cc" == "-" ]]; then
-    cc2asn | asn2ip
+    cc2asn - | asn2ip -
   else
-    cc2asn <<<"$cc" | asn2ip
+    cc2asn - <<<"$cc" | asn2ip -
   fi
 }
 
@@ -134,7 +134,7 @@ validate_asn() {
   else
     # format check
     if grep -Ev '^(-?|[aA][sS][0-9]+)$' <<<"$asn" > /dev/null; then
-      die "invalid ASN format"
+      die "invalid ASN"
     fi
   fi
 }
@@ -143,6 +143,7 @@ validate_asn() {
 validate_cc() {
   local cc=$1
 
+  # sanity check
   if [ -z "$cc" ]; then
     die "missing argument: [CC]"
   else
@@ -158,12 +159,18 @@ OPTIND=1
 while getopts ":achp:v" opt; do
   case $opt in
   a)
-    if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+    if [[ "$LASTOPT" == "$opt" ]]; then
+      die "only one \`-$opt' may be specified"
+    fi
+
     ACTION=asn2ip
     LASTOPT=$opt
     ;;
   c)
-    if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+    if [[ "$LASTOPT" == "$opt" ]]; then
+      die "only one \`$opt' may be specified"
+    fi
+
     ACTION=cc2asn
     LASTOPT=$opt
     ;;
@@ -173,11 +180,14 @@ while getopts ":achp:v" opt; do
     exit 0
     ;;
   p)
-    if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+    if [[ "$LASTOPT" == "$opt" ]]; then
+      die "only one \`$opt' may be specified"
+    fi
 
     # validate option argument
     if grep -Ev '^[0-9]+$' &>/dev/null <<<"$OPTARG"; then
-        short; exit 1
+      die "invalid option argument -- '$OPTARG'"
+      exit 1
     fi
 
     MAX=$((10#$OPTARG))
@@ -190,17 +200,26 @@ while getopts ":achp:v" opt; do
     exit 0
     ;;
   :)
-    die "-$OPTARG requires an argument"
+    die "option requires an argument -- '$OPTARG'"
     ;;
   \?)
-    die "invalid option: -- '$OPTARG'"
+    die "invalid option -- '$OPTARG'"
     ;;
   esac
 done;
 shift $((OPTIND-1))
 
 # check for empty arguments
-if [ $# -eq 0 ]; then short; exit 1; fi
+if [[ -n "$LASTOPT" && $# -eq 0 ]]; then
+  case $LASTOPT in
+    a) validate_asn; exit 1;;
+    c) validate_cc; exit 1;;
+    *) short; exit 1;;
+  esac
+elif [ $# -eq 0 ]; then
+  short
+  exit 1
+fi
 
 # main
 # release the kraken!
diff --git a/ipinfo b/ipinfo
--- a/ipinfo
+++ b/ipinfo
@@ -456,18 +456,22 @@ OPTIND=1
 while getopts ":df:hl:pv" opt; do
   case $opt in
     d)
-      if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+      if [[ "$LASTOPT" == "$opt" ]]; then
+        die "only one \`-$opt' may be specified"
+      fi
 
       DNS_SERVER=${DNS_SERVERS[$RANDOM % ${#DNS_SERVERS[@]}]}
       DNS_OPTION="$DNS_SERVER"
       LASTOPT=$opt
       ;;
     f)
-      if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+      if [[ "$LASTOPT" == "$opt" ]]; then
+        die "only one \`-$opt' may be specified"
+      fi
 
       # validate ranges
       if grep -E -v '^[0-9,-]+$' <<<"$OPTARG" &>/dev/null; then
-        die "invalid field list"
+        die "invalid field list -- '$OPTARG'"
       fi
 
       FIELD=$OPTARG
@@ -501,12 +505,14 @@ while getopts ":df:hl:pv" opt; do
           fi
           ;;
         *)
-          die "invalid option argument"
+          die "invalid option argument -- '$OPTARG'"
           ;;
       esac
       ;;
     p)
-      if [[ "$LASTOPT" == "$opt" ]]; then short; exit 1; fi
+      if [[ "$LASTOPT" == "$opt" ]]; then
+        die "only one \`-$opt' may be specified"
+      fi
 
       PROXY="on"
       LASTOPT=$opt
@@ -519,7 +525,7 @@ while getopts ":df:hl:pv" opt; do
       exit 0
       ;;
     :)
-      die "option \`-$OPTARG' requires an argument"
+      die "option requires an argument -- '$OPTARG'"
       ;;
     \?)
       die "invalid option -- '$OPTARG'"
@@ -529,7 +535,9 @@ done
 shift $((OPTIND - 1))
 
 # check for empty arguments
-if [ $# -eq 0 ]; then
+if [[ -n "$LASTOPT" && $# -eq 0 ]]; then
+  validate; exit 1
+elif [ $# -eq 0 ]; then
   short; exit 1
 fi
 
