crib: removed dependency on GNU parallel

diff --git a/crib b/crib
--- a/crib
+++ b/crib
@@ -10,13 +10,19 @@ PROG=$(basename $0)
 # default: CC to IP blocks
 ACTION=cc2ip
 
-# if GNU parallel is not installed
+# release the kraken!
 PARALLEL="xargs -n1 -P${MAX:=64} -I{}"
 
 # fanciful output
 b="\033[1m"  # bold
 u="\033[4m"  # underline
 o="\033[0m"  # off
+
+# clean up upon EXIT
+clean() {
+  rm /tmp/*.xargs &>/dev/null
+}
+trap "clean" EXIT
 
 # graceful death!
 die() {
@@ -63,25 +69,22 @@ EOF
 
 # return IP prefixes from ASN
 asn2ip() {
-  local asn=$1; validate_asn $asn
-  local command=!g
-  local server=whois.radb.net
+  local asn=$1
+  validate_asn $asn
 
   if [[ -z "$asn" || "$asn" == "-" ]]; then
     cat -
   else
     cat <<<"$asn"
-  fi | $PARALLEL whois -h $server "$command{}" 2>/dev/null | \
-      grep -Ev '^[ACD]' | tr -d '\n' | \
-        sed -r 's/(\/([0-9]|1[0-9]|2[0-9]|3[0-2]))/\1\n/g' | \
-          sed '/^$/d' | tr -d ' ' | \
-            sort -t. -n -k1,1 -k2,2 -k3,3 -k4,4 | \
-              uniq -c | awk '{ print $NF }'
+  fi | \
+  $PARALLEL sh -c 'whois -h whois.radb.net !g{} > /tmp/{}.xargs' 2>/dev/null
 
-# awk to the rescue againg
-# time cat ASN.txt | \
-#   xargs -n1 -P64 -I{} whois -h whois.radb.net '!g{}' 2>/dev/null | \
-#     awk 'BEGIN { RS="(A[0-9]+|[CD])"} { for (i=1; i <=NF; i++) print $i
+  # awk to the rescue again
+  cat /tmp/*.xargs | awk '\
+    BEGIN { RS = "(A[0-9]+|[CD])\n?"; FS = " "; }
+          { for (i = 1; i <= NF; i++) print $i  }' | \
+    tr -d "\n" | sed -r 's/(\/([0-9]|1[0-9]|2[0-9]|3[0-2]))/\1\n/g' | \
+      sort -t. -n -k1,1 -k2,2 -k3,3 -k4,4 | uniq -c | awk '{ print $NF }'
 }
 
 # return ASN from CC
@@ -198,11 +201,6 @@ while getopts ":achp:v" opt; do
 done;
 
 # main
-# is GNU parallel installed?
-if which parallel &>/dev/null; then
-  PARALLEL="parallel -j+${MAX:=64}"
-fi
-
 if [[ -z "$1" || "$1" == "-" ]]; then
   $ACTION -
 else
